# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a03cf88bc1b7965634fbad0cca71f77769609ad7c087cb8bffc193a7952957502e2e39509ba921834e8dd39835d4ae9ad78965f11c8e27561237c43915c1fc5c

test:
  secret_key_base: 22788362d2dc1441c7298cdc114248a84f1370ac2ebde15964bace6ee198ba36679947e2314f36b466a3459071906817ef2a425466ec500b2d01e392ca9e96af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
